-- ==========================================
-- THIS FILE HAS BEEN DEPRECATED
-- ==========================================
-- The secure RPC definitions now live exclusively in:
--   backend/functions/dashboard.sql
--   backend/correct_schema_reference.sql
--
-- DO NOT USE THIS FILE. It has been neutralized
-- to prevent accidental regression of security fixes.
-- ==========================================
